name: Promise-Q - build module
run-name: ${{ github.actor }} testing promise-Q
on: [push]
jobs:
    Setup:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - run: npm test

